-- 1) LOG_TYPE에 WARN 추가 (중복 방지)
INSERT INTO log_type (type_name)
SELECT 'WARN' FROM dual
WHERE NOT EXISTS (
    SELECT 1 FROM log_type WHERE type_name = 'WARN'
);

-- 2) CONTENT: trend FK/컬럼 제거, keyword 추가
ALTER TABLE content DROP CONSTRAINT fk_content_trend;
ALTER TABLE content DROP COLUMN trend_id;
ALTER TABLE content ADD (keyword VARCHAR2(200));

-- 3) LLM_CHANNEL: BASE_URL, TOP_P 컬럼 제거
ALTER TABLE llm_channel DROP COLUMN base_url;
ALTER TABLE llm_channel DROP COLUMN top_p;


INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('남성의류', '셔츠·바지·아우터 등 남성 일상복');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('여성의류', '블라우스·원피스·코트 등 여성 일상복');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('이너웨어/파자마', '속옷·잠옷·이너웨어 전반');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('여성슈즈', '플랫·힐·스니커즈·부츠 등 여성 신발');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('남성슈즈', '스니커즈·구두·워커 등 남성 신발');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('가방', '백팩·크로스백·지갑 등 각종 가방');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('패션잡화', '모자·장갑·벨트·선글라스 등 액세서리');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('악세사리', '귀걸이·반지·목걸이·팔찌 등 주얼리');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('스포츠용품', '운동복·요가매트·골프·홈트 용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('레저', '등산·낚시 등 레저 관련 용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('캠핑용품', '텐트·침낭·랜턴 등 캠핑 장비');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('침구', '이불·베개·담요 등 침구류');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('가구', '책상·의자·수납 등 가정·사무용 가구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('인테리어 소품', '시계·거울·조화 등 데코 소품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('고양이 용품', '캣타워·화장실·장난감 등 고양이용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('강아지 용품', '목줄·장난감·식기 등 반려견 용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('청소용품', '밀대·청소포·빗자루 등 청소 도구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('가정용 잡화', '타월·수납함·옷걸이 등 생활 잡화');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('차량관리/인테리어', '차량 시트·거치대·쿠션 등 인테리어');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('세차/카케어', '세차 타월·브러시·스펀지 등 카케어');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('오토바이 용품', '헬멧·장갑·부츠 등 라이딩 장비');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('사무용품', '펜·가위·포스트잇·바인더 등 문구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('주방도구', '냄비·프라이팬·식기·컵 등 조리도구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('주방잡화', '주방매트·행주·오프너 등 주방 소품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('생활가전', '청소기·세탁기·공기청정기 등 가전');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('주방가전', '전자레인지·에어프라이어·커피머신');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('뷰티헤어기기', '드라이어·고데기·면도기 등 뷰티 기기');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('유아용품', '유모차·유아식기·매트 등 육아 필수품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('완구 취미', '완구·취미용 소품 및 키트');