-- 1) LOG_TYPE에 WARN 추가 (중복 방지)
INSERT INTO log_type (type_name)
SELECT 'WARN' FROM dual
WHERE NOT EXISTS (
    SELECT 1 FROM log_type WHERE type_name = 'WARN'
);

-- 2) CONTENT: trend FK/컬럼 제거, keyword 추가
ALTER TABLE content DROP CONSTRAINT fk_content_trend;
ALTER TABLE content DROP COLUMN trend_id;
ALTER TABLE content ADD (keyword VARCHAR2(200));

-- 3) LLM_CHANNEL: BASE_URL, TOP_P 컬럼 제거
ALTER TABLE llm_channel DROP COLUMN base_url;
ALTER TABLE llm_channel DROP COLUMN top_p;

INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('INNERWEAR_AND_PAJAMAS', '속옷·브라·팬티·이너웨어·잠옷');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('SHOES', '남녀 스니커즈, 부츠, 힐, 슬리퍼, 구두 등 신발');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('BAGS', '백팩, 토트·크로스백, 클러치, 지갑, 노트북 가방, 캐리어');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('FASHION_ACCESSORIES', '벨트, 모자, 장갑, 선글라스, 스카프, 넥타이, 양말');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('JEWELRY_AND_ACCESSORIES', '귀걸이, 반지, 목걸이, 팔찌, 헤어 액세서리');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('SPORTS_GEAR', '운동복, 요가매트, 골프/홈트 용품, 운동기구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('LEISURE_GEAR', '등산·낚시 등 레저 의류·용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('CAMPING_GEAR', '텐트, 침낭, 해먹, 랜턴, 캠핑 장비');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('BEDDING', '이불, 베개, 담요, 침구세트, 매트/카펫');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('FURNITURE', '책상, 의자, 수납/선반, 옷걸이, 소파 등 가구');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('DECOR', '벽시계, 앨범/액자, 거울, 조화, 꽃병');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('CAT_SUPPLIES', '캣타워, 하우스, 매트, 식기, 화장실, 장난감, 빗, 스크래쳐');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('DOG_SUPPLIES', '강아지 옷, 식기, 목줄, 매트, 장난감, 빗, 신발');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('CLEANING_SUPPLIES', '밀대·청소포, 빗자루, 테이프클리너, 고무장갑, 행주');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('HOME_ESSENTIALS', '타월, 수납함, 옷걸이, 빨래통/건조대 등 생활잡화');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('CAR_INTERIOR_AND_CARE', '시트커버, 폰 거치대, 쿠션, 바닥/트렁크매트, 수납/정리용품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('CAR_WASH_AND_DETAILING', '세차 타월, 브러시, 스펀지, 먼지털이개');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('MOTORCYCLE_GEAR', '헬멧, 라이딩 의류, 장갑, 부츠, 보호장비');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('OFFICE_SUPPLIES', '펜, 가위, 포스트잇, 바인더, 스테이플러, 데스크 정리소품');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('COOKWARE_AND_UTENSILS', '냄비, 프라이팬, 접시, 수저/포크/나이프, 컵, 칼');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('KITCHEN_ACCESSORIES', '주방매트, 행주, 앞치마, 오프너, 타이머, 냄비받침');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('HOME_APPLIANCES', '청소기, 세탁기, 건조기, 공기청정기, 다리미 등 생활가전');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('KITCHEN_APPLIANCES', '전자레인지, 에어프라이어, 커피머신, 전기밥솥, 오븐, 블렌더');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('BEAUTY_AND_GROOMING_DEVICES', '드라이어, 고데기, 면도기, 트리머, 피부관리기기');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('BABY_PRODUCTS', '유모차, 유아식기, 매트, 아기띠, 침구, 기저귀백');
INSERT INTO PRODUCT_CATEGORY (NAME, DESCRIPTION) VALUES ('TOYS_AND_HOBBIES', '완구, 취미 키트, 공예 세트');
COMMIT;